server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log

  - job_name: app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: app
          log_type: application
          __path__: /var/log/myapp/app.log

  - job_name: access-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: app
          log_type: access
          __path__: /var/log/myapp/access_log.*.log

